---
# handlers file for role1
- name: Restart Apache
  ansible.builtin.service:
    name: httpd
    state: restarted

- name: Restart Firewalld
  ansible.builtin.service:
    name: firewalld
    state: restarted
